[server]
headless = true              # 브라우저 없이 서버만 실행 (기본값)
port = 8501                  # 실행 포트 (기본값 유지)
enableCORS = false           # 외부 접근 허용 (Streamlit Cloud 대응)
enableXsrfProtection = false # Safari, 모바일 환경 호환성 향상

[browser]
gatherUsageStats = false     # 사용자 통계 수집 안 함 (프라이버시 보호)

[theme]
base = "light"
primaryColor = "#1A73E8"              # 파란 계열 포인트 색
backgroundColor = "#FFFFFF"          # 전체 배경 (흰색)
secondaryBackgroundColor = "#F0F2F6" # 사이드바 배경
textColor = "#262730"                # 기본 글씨 색
font = "sans serif"                  # 가독성 높은 기본 폰트
